# Generated by Django 5.0.3 on 2024-03-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkaccount',
            name='creator',
            field=models.CharField(default='none', max_length=20, verbose_name='Автор запроса'),
        ),
    ]
