# Generated by Django 5.0.3 on 2024-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_vkaccount_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkaccount',
            name='first_name',
            field=models.CharField(default='null', max_length=200, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vkaccount',
            name='last_name',
            field=models.CharField(default='null', max_length=200, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
